--Script para criação do BD SIN
--CREATE DATABASE:SIN
CREATE SCHEMA IF NOT EXISTS SIN_HU;

CREATE TABLE IF NOT EXISTS SIN_HU.TAB_USU_USUARIOS(
USU_LOGIN VARCHAR(11) NOT NULL,
USU_SENHA VARCHAR(20) NOT NULL,
USU_NOME VARCHAR(60) NOT NULL,
PRIMARY KEY (USU_LOGIN)
);

CREATE TABLE IF NOT EXISTS SIN_HU.TAB_NUT_NUTRICIONISTA(
NUT_CDNUTRICIONISTA SERIAL,
USU_LOGIN VARCHAR(11) NOT NULL,
CONSTRAINT USU_LOGINFK FOREIGN KEY (USU_LOGIN) REFERENCES
SIN_HU.TAB_USU_USUARIOS(USU_LOGIN) ON UPDATE CASCADE,
UNIQUE(USU_LOGIN),
PRIMARY KEY(NUT_CDNUTRICIONISTA)
);

CREATE TABLE IF NOT EXISTS SIN_HU.TB_PAC_PACIENTE(
PAC_NRPRONTUARIO INTEGER,
PAC_FLADICIONADO BOOLEAN,
PRIMARY KEY(PAC_NRPRONTUARIO)
);

CREATE TABLE IF NOT EXISTS SIN_HU.TAB_ACN_ACOMP_NUTRI(
ACN_CDACOMP_NUTRI SERIAL,
ACN_DTTRIAGEM DATE,
ACN_RESULTADO VARCHAR(45),
ACN_REALIZACAO VARCHAR(45),
ACN_STACOMPANHAMENTO BOOLEAN,
PAC_NRPRONTUARIO INTEGER,
NUT_CDNUTRICIONISTA INTEGER,
CONSTRAINT PAC_NRPRONTUARIOFK FOREIGN KEY (PAC_NRPRONTUARIO)
REFERENCES SIN_HU.TB_PAC_PACIENTE(PAC_NRPRONTUARIO),
CONSTRAINT NUT_CDNUTRICIONISTAFK FOREIGN KEY (NUT_CDNUTRICIONISTA)
REFERENCES SIN_HU.TAB_NUT_NUTRICIONISTA(NUT_CDNUTRICIONISTA),
UNIQUE(PAC_NRPRONTUARIO),
PRIMARY KEY(ACN_CDACOMP_NUTRI)
);

CREATE TABLE IF NOT EXISTS SIN_HU.TAB_TOL_TOLERANCIA(
TOL_CDTOLERANCIA SERIAL,
TOL_TPTOLERANCIA VARCHAR(60),
PRIMARY KEY(TOL_CDTOLERANCIA)
);

CREATE TABLE IF NOT EXISTS SIN_HU.TAB_ACT_ACOMP_TOL(
TOL_CDTOLERANCIA INTEGER,
ACN_CDACOMP_NUTRI INTEGER,
CONSTRAINT TOL_CDTOLERANCIAFK FOREIGN KEY (TOL_CDTOLERANCIA)
REFERENCES SIN_HU.TAB_TOL_TOLERANCIA(TOL_CDTOLERANCIA),
CONSTRAINT ACN_CDACOMP_NUTRIFK FOREIGN KEY (ACN_CDACOMP_NUTRI)
REFERENCES SIN_HU.TAB_ACN_ACOMP_NUTRI(ACN_CDACOMP_NUTRI),
PRIMARY KEY(TOL_CDTOLERANCIA,ACN_CDACOMP_NUTRI)
);

CREATE TABLE IF NOT EXISTS SIN_HU.TAB_ACT_ACEITACAO_ALIMENTAR(
ACT_CDACEITACAO SERIAL,
ACT_TPACEITACAO VARCHAR(45),
ACT_DTACEITACAO DATE,
ACN_CDACOMP_NUTRI INTEGER,
CONSTRAINT ACN_CDACOMP_NUTRIFK FOREIGN KEY (ACN_CDACOMP_NUTRI)
REFERENCES SIN_HU.TAB_ACN_ACOMP_NUTRI(ACN_CDACOMP_NUTRI),
PRIMARY KEY(ACT_CDACEITACAO)
);

CREATE TABLE IF NOT EXISTS SIN_HU.TAB_AVA_AVALIACAO_ANTRO(
AVA_CDAVALIACAO SERIAL,
AVA_DTAVALIACAO DATE NOT NULL,
AVA_VLPESO DECIMAL(10,2) NOT NULL,
AVA_VLALTURA DECIMAL(10,2) NOT NULL,
AVA_VLIMC DECIMAL(10,2),
AVA_DSDIAGNOSTICO VARCHAR(60),
ACN_CDACOMP_NUTRI INTEGER,
CONSTRAINT ACN_CDACOMP_NUTRIFK FOREIGN KEY (ACN_CDACOMP_NUTRI)
REFERENCES SIN_HU.TAB_ACN_ACOMP_NUTRI(ACN_CDACOMP_NUTRI),
PRIMARY KEY(AVA_CDAVALIACAO)
);

CREATE TABLE IF NOT EXISTS SIN_HU.TAB_INS_INSUMOS(
INS_CDINSUMO SERIAL,
INS_NMINSUMO VARCHAR(100),
INS_STINSUMO BOOLEAN,
PRIMARY KEY(INS_CDINSUMO)
);

CREATE TABLE IF NOT EXISTS SIN_HU.TAB_SUP_SUPLEMENTOS(
SUP_CDSUPLEMENTO SERIAL,
SUP_DTINICIO DATE,
SUP_DTSUSPENSAO DATE,
SUP_NRVEZES_DIA INTEGER,
INS_CDINSUMO INTEGER,
ACN_CDACOMP_NUTRI INTEGER,
CONSTRAINT TAB_CDINSUMOFK FOREIGN KEY(INS_CDINSUMO)
REFERENCES SIN_HU.TAB_INS_INSUMOS(INS_CDINSUMO),
CONSTRAINT ACN_CDACOMP_NUTRIFK FOREIGN KEY (ACN_CDACOMP_NUTRI)
REFERENCES SIN_HU.TAB_ACN_ACOMP_NUTRI(ACN_CDACOMP_NUTRI),
PRIMARY KEY(SUP_CDSUPLEMENTO)
);

CREATE TABLE IF NOT EXISTS SIN_HU.TAB_DIE_DIETAS(
DEI_CDDIETA SERIAL,
DEI_VLVOLUME DECIMAL(10,2),
DEI_NRVEZES INTEGER,
DEI_VLVOL_PRESCRITO DECIMAL(10,2),
DEI_VLVOL_INFUNDIDO DECIMAL(10,2),
DEI_VLDESPERDICIO DECIMAL(10,2),
INS_CDINSUMO INTEGER,
ACN_CDACOMP_NUTRI INTEGER,
CONSTRAINT TAB_CDINSUMOFK FOREIGN KEY(INS_CDINSUMO)
REFERENCES SIN_HU.TAB_INS_INSUMOS(INS_CDINSUMO),
CONSTRAINT ACN_CDACOMP_NUTRIFK FOREIGN KEY (ACN_CDACOMP_NUTRI)
REFERENCES SIN_HU.TAB_ACN_ACOMP_NUTRI(ACN_CDACOMP_NUTRI),
PRIMARY KEY(DEI_CDDIETA)
);